[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
via_ir = true

[profile.default.fuzz]
runs = 256

[rpc_endpoints]
flare = "${FLARE_RPC_URL}"
coston2 = "${FLARE_TESTNET_RPC_URL}"

[etherscan]
flare = { key = "${FLARESCAN_API_KEY}", url = "https://flarescan.com/api" }
